device: auto
root_dir: output_testing
seed: 2
dataset:
  root: ../Data
  name: chain-5
  sem_name: linear # non-linear #non-additive
  splits: [ 0.8,0.1, 0.1 ]
  k_fold: 1
  shuffle_train: True
  loss: default
  scale: default
  num_samples: 2500
  base_version: 5 # dgfh
  base_distribution_name: normal_corr
  # don't have it as dict, it crashes with some assertions at cfg.merge_from_file(config_file)
  # enter in the form i, j, value, we are counting from 0 btw (node-wise)
  correlations: [[0, 1, .3], [1, 3, 20.4], [1, 2, 0.4]] 
  # correlations: [[0, 4, 20.0]]
  steps_correlations: 100
model:
  name: causal_nf
  layer_name: maf
  dim_inner: [32, 32, 32]
  num_layers: 1
  init: None
  act: elu
  adjacency: True
  base_to_data: False
  base_distr: normal
  learn_base: False
  plot: False
train:
  max_epochs: 10
  regularize: False
  kl: forward  # backward
  batch_size: 4096
  num_workers: 0
  limit_train_batches: None
  limit_val_batches: None
  max_time: 00:01:00:00
  inference_mode: False
optim:
  optimizer: adam
  base_lr: 0.001
  beta_1: 0.9
  beta_2: 0.999
  momentum: 0.0
  weight_decay: 0.0
  scheduler: plateau
  mode: min
  factor: 0.95
  patience: 60
  cooldown: 0