seed: [ 423626, 737 ]
device: [ cpu ]
root_dir: [ output_causal_nf/ablation_u_x ]
dataset:
  name: 'TODO'
  sem_name: 'TODO'
  root: [ ../Data ]
  splits: [ [ 0.8, 0.1, 0.1 ] ]
  k_fold: [ 1 ]
  shuffle_train: [ True ]
  loss: [ default ]
  scale: [ default ]
  num_samples: [ 25000 ]
  base_version: [ 0 ]
  base_distribution_name: [ 'multivariatenormal' ]
  # don't have it as dict, it crashes with some assertions at cfg.merge_from_file(config_file)
  # enter in the form i, j, value, we are counting from 0 btw (node-wise)
  correlations: [ 
    # [[0, 1, 0.0]],
    # [[0, 1, 0.5]],
    # [[0, 1, 0.8]],
    [[0, 1, 1.0]],
    [[0, 2, 1.0]],
    [[1, 2, 1.0]]
   ]
  means: [
    [[0, 0.], [1, 0.], [2, 0.]]
  ]
  variances: [
    [[0, 1.], [1, 1.], [2, 1.]]
  ]
  # bernoulli_coef: [
  #   [0.5, 0.5, 0.5, 0.5],
  #   [0.25, 0.75, 0.25, 0.95],
  #   [0.35, 0.45, 0.15, 0.05]
  # ]
  # uniform_a: [
  #   [1, 2, 4],
  #   [3, 5, 4]
  # ]
  # uniform_b: [
  #   [2, 3, 5],
  #   [8, 1, 5]
  # ]
  # multiple_distributions: [
  #   [
  #     ['Bernoulli', 0.7],
  #     ['Bernoulli', 0.2],
  #     ['Uniform', 0, 1]
  #   ],
  #   [
  #     ['Normal', 0, 1],
  #     ['Laplace', 0, 1],
  #     ['Uniform', 0, 1]
  #   ]
  # ]
  steps: [
    5
  ]
  
# base_distribution:
#   correlations: [ {"0_1": 1.0, "1_3": 0.4}, {"0_1": 1.0, "1_3": 0.7}]
model:
  name: [ causal_nf ]
  layer_name: [ maf ]
  dim_inner: [ [ 32 ] ]
  num_layers: [ 1 ]
  init: [ None ]
  act: [ elu ]
  adjacency: [ True ]
  base_to_data: [ True ]
  plot: [ False ]
train:
  max_epochs: [ 1000 ]
  regularize: [ True ]
  batch_size: [ 4000 ]
  inference_mode: [ False ]
  max_time: [ 00:24:00:00 ]
  enable_progress_bar: [ False ]
early_stopping:
  activate: [ False ]
  min_delta: [ 0.0 ]
  patience: [ 100 ]
  verbose: [ False ]
optim:
  optimizer: [ adam ]
  base_lr: [ 1e-3 ]
  beta_1: [ 0.9 ]
  beta_2: [ 0.999 ]
  momentum: [ 0.0 ]
  weight_decay: [ 0.0 ]
  scheduler: [ plateau ]
  mode: [ min ]
  factor: [ 0.95 ]
  patience: [ 60 ]
  cooldown: [ 0 ]